package com.vbforge.generics.type_erasure;

import java.util.ArrayList;
import java.util.List;

/**
 * Demonstrates type erasure behavior in Java Generics.
 * Shows what really happens at runtime and common workarounds / limitations.
 */
public class TypeErasure {

    // -------------------------------------------------------------------------
    //  Basic demonstration: type information is erased
    // -------------------------------------------------------------------------

    public static void addStringToList(List list) {
        list.add("secret string");
    }

    public static void demonstrateErasure() {
        List<Integer> numbers = new ArrayList<>();
        addStringToList(numbers);           // compiles!

        // Integer i = numbers.get(0);      // ClassCastException at runtime
        Object o = numbers.get(0);          // works — we get String
        System.out.println("Got: " + o.getClass().getSimpleName());
    }

    // -------------------------------------------------------------------------
    //  Most common compile-time vs runtime difference examples
    // -------------------------------------------------------------------------

    public static boolean isListOfStrings(List<?> list) {
        // This does NOT work the way most people expect
        // return list instanceof List<String>;     // compile error

        // This also does NOT tell you the generic type
        return list instanceof List;
    }

    // -------------------------------------------------------------------------
    //  Workarounds / patterns people use because of erasure
    // -------------------------------------------------------------------------

    /**
     * Classic pattern: store the runtime type explicitly
     */
    public static class GenericHolder<T> {
        private final Class<T> type;
        private T value;

        @SuppressWarnings("unchecked")
        public GenericHolder(Class<T> type) {
            this.type = type;
        }

        public void set(T value) {
            this.value = value;
        }

        public T get() {
            return value;
        }

        public boolean isInstance(Object obj) {
            return type.isInstance(obj);
        }

        @SuppressWarnings("unchecked")
        public T cast(Object obj) {
            return type.cast(obj);
        }
    }

    /**
     * Helper method showing runtime type checks with explicit Class token
     */
    public static <T> T safeCast(Object obj, Class<T> clazz) {
        if (clazz.isInstance(obj)) {
            return clazz.cast(obj);
        }
        throw new ClassCastException("Cannot cast " + obj.getClass() + " to " + clazz);
    }

    // -------------------------------------------------------------------------
    //  Arrays + generics — one of the most confusing parts of erasure
    // -------------------------------------------------------------------------

    @SuppressWarnings("unchecked")
    public static <T> T[] createArrayBadWay(Class<T> clazz, int size) {
        return (T[]) new Object[size];  // Erasures to Object[]; no runtime throw here
    }

    public static <T> T[] createArrayGoodWay(Class<T> clazz, int size) {
        // Recommended way — uses reflection
        return (T[]) java.lang.reflect.Array.newInstance(clazz, size);
    }

    // -------------------------------------------------------------------------
    //  Bridge methods example (you usually don't write them manually)
    // -------------------------------------------------------------------------

    public static abstract class StringConverter {
        public abstract String convert(Object obj);

        // Bridge method generated by compiler:
        // public Object convert(Object obj) { return convert((String) obj); }
    }
}