name: Update README

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate README
        run: |
          echo "# VBForge Sandbox" > README.md
          echo "" >> README.md
          echo "Collection of small labs, demos and investigations." >> README.md
          echo "---" >> README.md
          echo "![Java](https://img.shields.io/badge/Java-17-orange)" >> README.md
          echo "![Spring](https://img.shields.io/badge/Spring-Boot-green)" >> README.md
          echo "![Docker](https://img.shields.io/badge/Docker-ready-blue)" >> README.md
          echo "" >> README.md

          echo "## Project Statistics" >> README.md
          echo "" >> README.md

          # Count projects per domain
          for domain in */ ; do
            count=0
            for project in "$domain"*/ ; do
              if [ -d "$project" ]; then
                count=$((count+1))
              fi
            done

            domain_name=$(basename "$domain")
            echo "$domain_name: $count  " >> README.md
          done

          echo "" >> README.md
          echo "## Projects" >> README.md
          echo "" >> README.md

          echo "| Domain | Project | Description |" >> README.md
          echo "|------|------|------|" >> README.md

          for domain in */ ; do
            for project in "$domain"*/ ; do

              if [ -f "$project/README.md" ]; then
                name=$(basename "$project")
                domain_name=$(basename "$domain")

                desc=$(grep -m 1 -v '^#' "$project/README.md" | sed 's/^ *//')

                echo "| $domain_name | [$name]($project) | $desc |" >> README.md
              fi

            done
          done

      - name: Commit README
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Auto update README" || echo "No changes"
          git push